-- migrate:up
CREATE TABLE IF NOT EXISTS pangkats (
    id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(5) NOT NULL UNIQUE,
    golongan VARCHAR(255) NOT NULL UNIQUE,
    is_active ENUM('0', '1') NOT NULL DEFAULT '0',
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE IF EXISTS pangkats