-- migrate:up
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    pangkat_id TINYINT UNSIGNED NOT NULL REFERENCES pangkats (id) ON UPDATE CASCADE,
    jabatan_id SMALLINT UNSIGNED NOT NULL REFERENCES jabatans (id) ON UPDATE CASCADE,
    name VARCHAR(255) NOT NULL,
    nik CHAR(16) NOT NULL UNIQUE COMMENT 'Panjang nik 16 digit',
    nip CHAR(18) NOT NULL UNIQUE COMMENT 'Panjang nip 18 digit',
    is_active ENUM('0', '1') NOT NULL DEFAULT '0',
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY (jabatan_id)
);

-- migrate:down
DROP TABLE IF EXISTS employees